CREATE TABLE IF NOT EXISTS crm_users (
 id CHAR(36) PRIMARY KEY, name VARCHAR(150) NOT NULL,
 email VARCHAR(254) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
 role VARCHAR(20) NOT NULL DEFAULT 'customer'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_sessions (
 token_hash CHAR(64) PRIMARY KEY, user_id CHAR(36) NOT NULL, expires_at DATETIME NOT NULL,
 FOREIGN KEY (user_id) REFERENCES crm_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_leads (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, customer VARCHAR(150) NOT NULL, phone VARCHAR(20) NOT NULL,
 city VARCHAR(150) NOT NULL, service VARCHAR(255) NOT NULL, source VARCHAR(255) NOT NULL DEFAULT 'Website',
 date DATE NOT NULL, status VARCHAR(30) NOT NULL DEFAULT 'New', follow_up DATE NULL, notes TEXT NOT NULL,
 payment_id VARCHAR(100) NULL UNIQUE, order_id VARCHAR(100) NULL, amount DECIMAL(12,2) NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 INDEX lead_date (date), INDEX lead_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS crm_lead_assignments (
 lead_id BIGINT UNSIGNED PRIMARY KEY,
 employee_id CHAR(36) NOT NULL,
 FOREIGN KEY (lead_id) REFERENCES crm_leads(id) ON DELETE CASCADE,
 FOREIGN KEY (employee_id) REFERENCES crm_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
