import { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Users, UserPlus, Phone, CalendarCheck, Star, ThumbsDown, CircleCheck, CalendarDays, Clock, Search, Plus, X } from 'lucide-react';
import StatCard from '../components/StatCard';
import LeadTable from '../components/LeadTable';
import { dummyLeads } from '../data/dummyLeads';
const statuses=['New','Contacted','Follow Up','Interested','Not Interested','Converted'];
const storageKey='jaypro-admin-leads-v1';
const today=()=>{const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');};
const normalize=v=>/^\d{2}-\d{2}-\d{4}$/.test(v || '')?v.split('-').reverse().join('-'):v;
const initial=()=>{try {const saved=JSON.parse(localStorage.getItem(storageKey));if(Array.isArray(saved)&&saved.every(l=>l && ['id','customer','phone','city','service','source','date','status'].every(k=>typeof l[k]==='string')))return saved;}catch{}return dummyLeads.map(l=>({...l,date:normalize(l.date),followUp:normalize(l.followUp)}));};
const blank=()=>({customer:'',phone:'',city:'',service:'',source:'Website',date:today(),status:'New',followUp:'',notes:''});
export default function AllLeads(){
 const [leads,setLeads]=useState(initial),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[editor,setEditor]=useState(null),[readOnly,setReadOnly]=useState(false),[error,setError]=useState('');
 const dialog=useRef(null);const {pathname}=useLocation();const navigate=useNavigate();const page=pathname.split('/').pop();
 useEffect(()=>{setSearch('');setStatus('');setEditor(page==='add-lead'?blank():null);setReadOnly(false);},[page]);
 useEffect(()=>{if(editor&&!dialog.current?.open)dialog.current?.showModal();},[editor]);
 const close=()=>{setEditor(null);if(page==='add-lead')navigate('/admin/leads');};
 const save=e=>{e.preventDefault();const lead={...editor,customer:editor.customer.trim(),city:editor.city.trim(),service:editor.service.trim()};if(!lead.customer||!lead.city||!lead.service)return;const next=lead.id?leads.map(l=>l.id===lead.id?lead:l):[...leads,{...lead,id:'L'+String(Math.max(0,...leads.map(l=>Number(l.id.replace(/^L/,''))||0))+1).padStart(3,'0')}];try{localStorage.setItem(storageKey,JSON.stringify(next));setError('');}catch{setError('Browser storage is unavailable. Changes will only last for this session.');}setLeads(next);close();};
 const routeStatus={'new-leads':'New','follow-ups':'Follow Up',interested:'Interested',converted:'Converted'}[page];
 const filtered=leads.filter(l=>(!routeStatus||l.status===routeStatus)&&(!status||l.status===status)&&[l.customer,l.phone,l.city,l.service,l.id].some(v=>v.toLowerCase().includes(search.trim().toLowerCase())));
 const stats=[['TOTAL LEADS',leads.length,Users,'#635bff'],...statuses.map((s,i)=>[s==='New'?'NEW LEADS':s.toUpperCase(),leads.filter(l=>l.status===s).length,[UserPlus,Phone,CalendarCheck,Star,ThumbsDown,CircleCheck][i],['#4785ff','#efb400','#ff822a','#17c964','#f04461','#0ebc91'][i]]),["TODAY'S LEADS",leads.filter(l=>l.date===today()).length,CalendarDays,'#935cff'],["TODAY'S FOLLOW-UPS",leads.filter(l=>l.followUp===today()).length,Clock,'#f33e94']];
 if(page==='settings')return <section className="admin-settings"><h2>Workspace settings</h2><p>Lead records are stored in this browser. The initial records are sample data.</p><p>Your account and sign-in are managed by the existing Jaypro authentication system.</p><label>Storage mode<input value="Local browser storage" readOnly/></label></section>;
 return <><div className="stats-grid">{stats.map(([title,value,icon,color])=><StatCard key={title} {...{title,value,icon,color}}/>)}</div>{error&&<p role="alert" className="admin-notice">{error}</p>}<section className="lead-management"><div className="lead-management-header"><h2>Lead Management</h2><div className="lead-tools"><label className="admin-search"><Search size={14}/><input aria-label="Search leads" placeholder="Search name, phone, city..." value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{statuses.map(s=><option key={s}>{s}</option>)}</select><button className="add-lead-btn" onClick={()=>{setReadOnly(false);setEditor(blank());}}><Plus size={14}/>Add New Lead</button></div></div><LeadTable leads={filtered} onView={l=>{setReadOnly(true);setEditor({...l});}} onEdit={l=>{setReadOnly(false);setEditor({...l});}}/><div className="admin-table-footer">{filtered.length} of {leads.length} leads<span>Saved in this browser</span></div></section>
 {editor&&<dialog ref={dialog} className="admin-dialog" aria-labelledby="lead-dialog-title" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}}><div className="admin-dialog-heading"><h2 id="lead-dialog-title">{readOnly?'Lead details':editor.id?'Edit lead':'Add new lead'}</h2><button aria-label="Close dialog" onClick={close}><X size={20}/></button></div><form onSubmit={save}><div className="admin-form-grid">{[['customer','Customer name','text'],['phone','Phone (10 digits)','tel'],['city','City','text'],['service','Service','text'],['source','Source','text'],['date','Date','date'],['followUp','Follow-up date','date']].map(([key,label,type])=><label key={key}>{label}<input autoFocus={key==='customer'} type={type} required={key!=='followUp'} pattern={key==='phone'?'[0-9]{10}':undefined} readOnly={readOnly} value={editor[key]||''} onChange={e=>setEditor({...editor,[key]:e.target.value})}/></label>)}<label>Status<select disabled={readOnly} value={editor.status} onChange={e=>setEditor({...editor,status:e.target.value})}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label className="admin-form-wide">Notes<textarea rows={3} readOnly={readOnly} value={editor.notes||''} onChange={e=>setEditor({...editor,notes:e.target.value})}/></label></div><div className="admin-form-actions"><button type="button" onClick={close}>Close</button>{!readOnly&&<button className="add-lead-btn" type="submit">Save lead</button>}</div></form></dialog>}</>;
}
