BEGIN;

-- Separate names keep previously created CRM tables/data intact during migration.
CREATE TABLE public.jaypro_profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'employee', 'admin')),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE FUNCTION public.jaypro_create_profile()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  -- Never grant roles from signup user_metadata: users can change that metadata.
  INSERT INTO public.jaypro_profiles (id, name, email, role)
  VALUES (NEW.id, left(coalesce(nullif(NEW.raw_user_meta_data->>'name', ''), NEW.email, 'Customer'), 150), NEW.email, 'customer');
  RETURN NEW;
END;
$$;
REVOKE ALL ON FUNCTION public.jaypro_create_profile() FROM PUBLIC, anon, authenticated;
CREATE TRIGGER jaypro_auth_user_created AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.jaypro_create_profile();

INSERT INTO public.jaypro_profiles (id, name, email)
SELECT id, left(coalesce(nullif(raw_user_meta_data->>'name', ''), email, 'Customer'), 150), email
FROM auth.users WHERE email IS NOT NULL ON CONFLICT (id) DO NOTHING;

CREATE TABLE public.jaypro_leads (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer text NOT NULL CHECK (length(customer) BETWEEN 1 AND 150),
  phone text NOT NULL CHECK (phone ~ '^[0-9]{10}$'),
  city text NOT NULL DEFAULT '',
  service text NOT NULL,
  source text NOT NULL DEFAULT 'Website',
  date date NOT NULL DEFAULT CURRENT_DATE,
  status text NOT NULL DEFAULT 'New' CHECK (status IN ('New', 'Contacted', 'Follow Up', 'Interested', 'Not Interested', 'Converted')),
  "followUp" date,
  notes text NOT NULL DEFAULT '' CHECK (length(notes) <= 10000),
  "paymentId" text UNIQUE,
  "orderId" text UNIQUE,
  amount numeric(12,2),
  "employeeId" uuid REFERENCES public.jaypro_profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jaypro_leads_employee_created ON public.jaypro_leads("employeeId", created_at DESC, id DESC);
CREATE INDEX jaypro_leads_created ON public.jaypro_leads(created_at DESC, id DESC);

CREATE TABLE public.jaypro_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.jaypro_profiles(id) ON DELETE CASCADE,
  text text NOT NULL CHECK (length(text) BETWEEN 1 AND 4000),
  sender text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX jaypro_messages_user_created ON public.jaypro_messages(user_id, created_at, id);

-- Only Edge Functions can read/write these tables; browsers cannot bypass routing permissions.
ALTER TABLE public.jaypro_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jaypro_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jaypro_messages ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.jaypro_profiles, public.jaypro_leads, public.jaypro_messages FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.jaypro_leads_id_seq, public.jaypro_messages_id_seq FROM PUBLIC, anon, authenticated;
GRANT ALL ON public.jaypro_profiles, public.jaypro_leads, public.jaypro_messages TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.jaypro_leads_id_seq, public.jaypro_messages_id_seq TO service_role;

-- Row updates are atomic: retries cannot duplicate a lead or reset a later CRM status.
CREATE FUNCTION public.jaypro_verify_payment(p_order_id text, p_payment_id text)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
  UPDATE public.jaypro_leads
  SET status = CASE WHEN "paymentId" IS NULL THEN 'Converted' ELSE status END,
      "paymentId" = p_payment_id,
      updated_at = now()
  WHERE "orderId" = p_order_id AND ("paymentId" IS NULL OR "paymentId" = p_payment_id);
  RETURN FOUND;
END;
$$;
REVOKE ALL ON FUNCTION public.jaypro_verify_payment(text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.jaypro_verify_payment(text, text) TO service_role;

COMMIT;
