name: Deploy React Frontend to GoDaddy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build React frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy frontend to GoDaddy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ ftp.jayproinfratech.com }}
          username: ${{ irp0jc3pzrhi }}
          password: ${{ Jaypor@1234567 }}
          server-dir: public_html/
          local-dir: ./frontend/dist/